# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


    Animal.create(name: "Aardvark", wings:false, legs:true, tail: true)
    Animal.create(name: "Albatross", wings:true, legs:true, tail: true)
    Animal.create(name: "Alligator", wings:false, legs:true, tail: true)
    Animal.create(name: "Alpaca", wings:false, legs:true, tail: true)
    Animal.create(name: "Ant", wings:true, legs:true, tail: false)
    Animal.create(name: "Anteater", wings:false, legs:true, tail: true)
    Animal.create(name: "Antelope", wings:false, legs:true, tail: false)
    Animal.create(name: "Ape", wings: false, legs: true, tail: false)
    Animal.create(name: "Armadillo", wings: false, legs: true, tail: true)
    Animal.create(name: "Axolotl", wings: false, legs: true, tail: true)
    Animal.create(name: "Baboon", wings: false, legs: true, tail: false)
    Animal.create(name: "Badger", wings: false, legs: true, tail: true)
    Animal.create(name: "Barracuda", wings: false, legs: false, tail: true)
    Animal.create(name: "Bat", wings: true, legs: true, tail: false)
    Animal.create(name: "Bear", wings: false, legs: true, tail: false)
    Animal.create(name: "Beaver", wings: false, legs: true, tail: true)
    Animal.create(name: "Bee", wings: true, legs: true, tail: false)
    Animal.create(name: "Bison", wings: false, legs: true, tail: false)
    Animal.create(name: "Boar", wings: false, legs: true, tail: true)
    Animal.create(name: "Buffalo", wings: false, legs: true, tail: false)
    Animal.create(name: "Butterfly", wings: true, legs: true, tail: false)
    Animal.create(name: "Camel", wings: false, legs: true, tail: true)
    Animal.create(name: "Capybara", wings: false, legs: true, tail: false)
    Animal.create(name: "Caribou", wings: false, legs: true, tail: true)
    Animal.create(name: "Cassowary", wings: true, legs: true, tail: false)
    Animal.create(name: "Cat", wings: false, legs: true, tail: true)
    Animal.create(name: "Caterpillar", wings: false, legs: true, tail: false)
    Animal.create(name: "Cattle", wings: false, legs: true, tail: true)
    Animal.create(name: "Chamois", wings: false, legs: true, tail: false)
    Animal.create(name: "Cheetah", wings: false, legs: true, tail: true)
    Animal.create(name: "Chicken", wings: true, legs: true, tail: true)
    Animal.create(name: "Chimpanzee", wings: false, legs: true, tail: false)
    Animal.create(name: "Chinchilla", wings: false, legs: true, tail: true)
    Animal.create(name: "Chough", wings: true, legs: true, tail: true)
    Animal.create(name: "Clam", wings: false, legs: false, tail: true)
    Animal.create(name: "Cobra", wings: false, legs: false, tail: true)
    Animal.create(name: "Cockroach", wings: true, legs: true, tail: false)
    Animal.create(name: "Cod", wings: false, legs: false, tail: true)
    Animal.create(name: "Cormorant", wings: true, legs: true, tail: true)
    Animal.create(name: "Coyote", wings: false, legs: true, tail: true)
    Animal.create(name: "Crab", wings: false, legs: true, tail: false)
    Animal.create(name: "Crane", wings: true, legs: true, tail: true)
    Animal.create(name: "Crocodile", wings: false, legs: true, tail: true)
    Animal.create(name: "Crow", wings: true, legs: true, tail: true)
    Animal.create(name: "Curlew", wings: true, legs: true, tail: true)
    Animal.create(name: "Deer", wings: false, legs: true, tail: true)
    # Animal.create(name: "Dinosaur", wings: false, legs: true, tail: true)
    Animal.create(name: "Dog", wings: false, legs: true, tail: true)
    Animal.create(name: "Dogfish", wings: false, legs: false, tail: true)
    Animal.create(name: "Donkey", wings: false, legs: true, tail: true)
    Animal.create(name: "Dolphin", wings: false, legs: false, tail: true)
    Animal.create(name: "Dotterel", wings: true, legs: true, tail: true)
    Animal.create(name: "Dove", wings: true, legs: true, tail: true)
    Animal.create(name: "Dragonfly", wings: true, legs: true, tail: true)
    Animal.create(name: "Duck", wings: true, legs: true, tail: true)
    Animal.create(name: "Dugong", wings: false, legs: false, tail: true)
    Animal.create(name: "Dunlin", wings: true, legs: true, tail: true)
    Animal.create(name: "Eagle", wings: true, legs: true, tail: true)
    Animal.create(name: "Echidna", wings: false, legs: true, tail: false)
    Animal.create(name: "Eel", wings: false, legs: false, tail: true)
    Animal.create(name: "Eland", wings: false, legs: true, tail: true)
    Animal.create(name: "Elephant", wings: false, legs: true, tail: true)
    Animal.create(name: "Elk", wings: false, legs: true, tail: true)
    Animal.create(name: "Emu", wings: true, legs: true, tail: false)
    Animal.create(name: "Falcon", wings: true, legs: true, tail: true)
    Animal.create(name: "Ferret", wings: false, legs: true, tail: true)
    Animal.create(name: "Finch", wings: true, legs: true, tail: true)
    # Animal.create(name: "Fish", wings: false, legs: true, tail: true)
    Animal.create(name: "Flamingo", wings: true, legs: true, tail: true)
    Animal.create(name: "Fly", wings: true, legs: true, tail: true)
    Animal.create(name: "Fox", wings: false, legs: true, tail: true)
    Animal.create(name: "Frog", wings: false, legs: true, tail: true)
    Animal.create(name: "Gaur", wings: false, legs: true, tail: true)
    Animal.create(name: "Gazelle", wings: false, legs: true, tail: true)
    Animal.create(name: "Gerbil", wings: false, legs: true, tail: true)
    Animal.create(name: "Giraffe", wings: false, legs: true, tail: true)
    Animal.create(name: "Gnat", wings: true, legs: true, tail: true)
    Animal.create(name: "Gnu", wings: false, legs: true, tail: true)
    Animal.create(name: "Goat", wings: false, legs: true, tail: true)
    Animal.create(name: "Goldfinch", wings: true, legs: true, tail: true)
    Animal.create(name: "Goldfish", wings: false, legs: false, tail: true)
    Animal.create(name: "Goose", wings: true, legs: true, tail: true)
    Animal.create(name: "Gorilla", wings: false, legs: true, tail: true)
    Animal.create(name: "Goshawk", wings: true, legs: true, tail: true)
    Animal.create(name: "Grasshopper", wings: true, legs: true, tail: false)
    Animal.create(name: "Grouse", wings: true, legs: true, tail: true)
    Animal.create(name: "Guanaco", wings: false, legs: true, tail: true)
    Animal.create(name: "Gull", wings: true, legs: true, tail: true)
    Animal.create(name: "Hamster", wings: false, legs: true, tail: true)
    Animal.create(name: "Hare", wings: false, legs: true, tail: true)
    Animal.create(name: "Hawk", wings: true, legs: true, tail: true)
    Animal.create(name: "Hedgehog", wings: false, legs: true, tail: true)
    Animal.create(name: "Heron", wings: true, legs: true, tail: true)
    Animal.create(name: "Herring", wings: false, legs: false, tail: true)
    Animal.create(name: "Hornet", wings: true, legs: true, tail: true)
    Animal.create(name: "Hippopotamus", wings: false, legs: true, tail: true)
    Animal.create(name: "Horse", wings: false, legs: true, tail: true)
    Animal.create(name: "Human", wings: false, legs: true, tail: false)
    Animal.create(name: "Hummingbird", wings: true, legs: true, tail: true)
    Animal.create(name: "Hyena", wings: false, legs: true, tail: true)
    Animal.create(name: "Ibex", wings: false, legs: true, tail: true)
    Animal.create(name: "Ibis", wings: true, legs: true, tail: true)
    Animal.create(name: "Jackal", wings: false, legs: true, tail: true)
    Animal.create(name: "Jaguar", wings: false, legs: true, tail: true)
    Animal.create(name: "Jay", wings: true, legs: true, tail: true)
    Animal.create(name: "Jellyfish", wings: false, legs: false, tail: true)
    Animal.create(name: "Kangaroo", wings: false, legs: true, tail: true)
    Animal.create(name: "Kingfisher", wings: true, legs: true, tail: true)
    Animal.create(name: "Koala", wings: false, legs: true, tail: true)
    Animal.create(name: "Kookabura", wings: true, legs: true, tail: true)
    Animal.create(name: "Kouprey", wings: false, legs: true, tail: true)
    Animal.create(name: "Kudu", wings: false, legs: true, tail: true)
    Animal.create(name: "Lapwing", wings: true, legs: true, tail: true)
    Animal.create(name: "Lark", wings: true, legs: true, tail: true)
    Animal.create(name: "Lemur", wings: false, legs: true, tail: true)
    Animal.create(name: "Leopard", wings: false, legs: true, tail: true)
    Animal.create(name: "Lion", wings: false, legs: true, tail: true)
    Animal.create(name: "Llama", wings: false, legs: true, tail: true)
    Animal.create(name: "Lobster", wings: false, legs: true, tail: true)
    Animal.create(name: "Locust", wings: true, legs: true, tail: true)
    Animal.create(name: "Loris", wings: false, legs: true, tail: true)
    Animal.create(name: "Louse", wings: false, legs: true, tail: true)
    Animal.create(name: "Lyrebird", wings: true, legs: true, tail: true)
    Animal.create(name: "Magpie", wings: true, legs: true, tail: true)
    Animal.create(name: "Mallard", wings: true, legs: true, tail: true)
    Animal.create(name: "Manatee", wings: false, legs: false, tail: true)
    Animal.create(name: "Mandrill", wings: false, legs: true, tail: true)
    Animal.create(name: "Mantis", wings: true, legs: true, tail: true)
    Animal.create(name: "Marten", wings: false, legs: true, tail: true)
    Animal.create(name: "Meerkat", wings: false, legs: true, tail: true)
    Animal.create(name: "Mink", wings: false, legs: true, tail: true)
    Animal.create(name: "Mole", wings: false, legs: true, tail: false)
    Animal.create(name: "Mongoose", wings: false, legs: true, tail: true)
    Animal.create(name: "Monkey", wings: false, legs: true, tail: true)
    Animal.create(name: "Moose", wings: false, legs: true, tail: true)
    Animal.create(name: "Mosquito", wings: true, legs: true, tail: true)
    Animal.create(name: "Mouse", wings: false, legs: true, tail: true)
    Animal.create(name: "Mule", wings: false, legs: true, tail: true)
    Animal.create(name: "Narwhal", wings: false, legs: false, tail: true)
    Animal.create(name: "Newt", wings: false, legs: true, tail: true)
    Animal.create(name: "Nightingale", wings: true, legs: true, tail: true)
    Animal.create(name: "Octopus", wings: false, legs: true, tail: true)
    Animal.create(name: "Okapi", wings: false, legs: true, tail: true)
    Animal.create(name: "Opossum", wings: false, legs: true, tail: true)
    Animal.create(name: "Oryx", wings: false, legs: true, tail: true)
    Animal.create(name: "Ostrich", wings: true, legs: true, tail: true)
    Animal.create(name: "Otter", wings: false, legs: true, tail: true)
    Animal.create(name: "Owl", wings: true, legs: true, tail: true)
    Animal.create(name: "Oyster", wings: false, legs: false, tail: true)
    Animal.create(name: "Panther", wings: false, legs: true, tail: true)
    Animal.create(name: "Parrot", wings: true, legs: true, tail: true)
    Animal.create(name: "Partridge", wings: true, legs: true, tail: true)
    Animal.create(name: "Peafowl", wings: true, legs: true, tail: true)
    Animal.create(name: "Pelican", wings: true, legs: true, tail: true)
    Animal.create(name: "Penguin", wings: true, legs: true, tail: true)
    Animal.create(name: "Pheasant", wings: true, legs: true, tail: true)
    Animal.create(name: "Pig", wings: false, legs: true, tail: true)
    Animal.create(name: "Pigeon", wings: true, legs: true, tail: true)
    Animal.create(name: "Pony", wings: false, legs: true, tail: true)
    Animal.create(name: "Porcupine", wings: false, legs: true, tail: true)
    Animal.create(name: "Porpoise", wings: false, legs: true, tail: true)
    Animal.create(name: "Quail", wings: true, legs: true, tail: true)
    Animal.create(name: "Quelea", wings: true, legs: true, tail: true)
    Animal.create(name: "Quetzal", wings: true, legs: true, tail: true)
    Animal.create(name: "Rabbit", wings: false, legs: true, tail: true)
    Animal.create(name: "Raccoon", wings: false, legs: true, tail: true)
    Animal.create(name: "Rail", wings: true, legs: true, tail: true)
    Animal.create(name: "Ram", wings: false, legs: true, tail: true)
    Animal.create(name: "Rat", wings: false, legs: true, tail: true)
    Animal.create(name: "Raven", wings: true, legs: true, tail: true)
    Animal.create(name: "Red deer", wings: false, legs: true, tail: true)
    Animal.create(name: "Red panda", wings: false, legs: true, tail: true)
    Animal.create(name: "Reindeer", wings: false, legs: true, tail: true)
    Animal.create(name: "Rhinoceros", wings: false, legs: true, tail: false)
    Animal.create(name: "Rook", wings: true, legs: true, tail: true)
    Animal.create(name: "Salamander", wings: false, legs: true, tail: true)
    Animal.create(name: "Salmon", wings: false, legs: false, tail: true)
    Animal.create(name: "Sand Dollar", wings: false, legs: false, tail: true)
    Animal.create(name: "Sandpiper", wings: true, legs: true, tail: true)
    Animal.create(name: "Sardine", wings: false, legs: false, tail: true)
    Animal.create(name: "Scorpion", wings: false, legs: true, tail: true)
    Animal.create(name: "Seahorse", wings: false, legs: false, tail: true)
    Animal.create(name: "Seal", wings: false, legs: false, tail: true)
    Animal.create(name: "Shark", wings: false, legs: false, tail: true)
    Animal.create(name: "Sheep", wings: false, legs: true, tail: true)
    Animal.create(name: "Shrew", wings: false, legs: true, tail: true)
    Animal.create(name: "Skunk", wings: false, legs: true, tail: true)
    Animal.create(name: "Snail", wings: false, legs: false, tail: true)
    Animal.create(name: "Snake", wings: false, legs: false, tail: true)
    Animal.create(name: "Sparrow", wings: true, legs: true, tail: true)
    Animal.create(name: "Spider", wings: false, legs: true, tail: false)
    Animal.create(name: "Spoonbill", wings: true, legs: true, tail: true)
    Animal.create(name: "Squid", wings: false, legs: true, tail: false)
    Animal.create(name: "Squirrel", wings: false, legs: true, tail: true)
    Animal.create(name: "Starling", wings: true, legs: true, tail: true)
    Animal.create(name: "Stingray", wings: false, legs: false, tail: true)
    Animal.create(name: "Stinkbug", wings: true, legs: true, tail: true)
    Animal.create(name: "Stork", wings: true, legs: true, tail: true)
    Animal.create(name: "Swallow", wings: true, legs: true, tail: true)
    Animal.create(name: "Swan", wings: true, legs: true, tail: true)
    Animal.create(name: "Tapir", wings: false, legs: true, tail: true)
    Animal.create(name: "Tarsier", wings: false, legs: true, tail: true)
    Animal.create(name: "Termite", wings: false, legs: true, tail: false)
    Animal.create(name: "Tiger", wings: false, legs: true, tail: true)
    Animal.create(name: "Toad", wings: false, legs: true, tail: true)
    Animal.create(name: "Trout", wings: false, legs: false, tail: true)
    Animal.create(name: "Turkey", wings: true, legs: true, tail: true)
    Animal.create(name: "Turtle", wings: false, legs: true, tail: true)
    Animal.create(name: "Uakari" , wings: false, legs: true, tail: true)
    Animal.create(name: "Umbrella Bird" , wings: true, legs: true, tail: true)
    Animal.create(name: "Viper", wings: false, legs: false, tail: true)
    Animal.create(name: "Vulture", wings: true, legs: true, tail: true)
    Animal.create(name: "Wallaby", wings: false, legs: true, tail: true)
    Animal.create(name: "Walrus", wings: false, legs: false, tail: true)
    Animal.create(name: "Wasp", wings: true, legs: true, tail: true)
    Animal.create(name: "Weasel", wings: false, legs: true, tail: true)
    Animal.create(name: "Whale", wings: false, legs: false, tail: true)
    Animal.create(name: "Wildcat", wings: false, legs: true, tail: true)
    Animal.create(name: "Wolf", wings: false, legs: true, tail: true)
    Animal.create(name: "Wolverine", wings: false, legs: true, tail: true)
    Animal.create(name: "Wombat", wings: false, legs: true, tail: true)
    Animal.create(name: "Woodcock", wings: true, legs: true, tail: true)
    Animal.create(name: "Woodpecker", wings: true, legs: true, tail: true)
    Animal.create(name: "Worm", wings: false, legs: false, tail: true)
    Animal.create(name: "Wren", wings: true, legs: true, tail: true)
    Animal.create(name: "Xantus Hummingbird", wings: true, legs: true, tail: true)
    Animal.create(name: "Xolo", wings: false, legs: true, tail: true)
    Animal.create(name:"Yap monarch", wings: true, legs: true, tail: true)
    Animal.create(name: "Yak", wings: false, legs: true, tail: true)
    Animal.create(name: "Zebra", wings: false, legs: true, tail: true)
    Animal.create(name: "Zebra Finch", wings: true, legs: true, tail: true)
    Animal.create(name: "Zorilla", wings: false, legs: true, tail: true)
    Animal.create(name: "None", wings: true, legs: true, tail: true)
    


        
    # Chimera.create(name: "Griper", wings: "Albatross", legs: "Yak", tail: "Anteater", torso: "Alligator", head: "Tapir")
    # Blender.create(animal_id: 2, chimera_id:1)
    # Blender.create(animal_id: 4, chimera_id:1)
    # Blender.create(animal_id: 6, chimera_id:1)
    # Blender.create(animal_id: 3, chimera_id:1)
    # Need to add habitat


    # Habitat.create(name: , temperature: , traits: )
    Habitat.create(name: "Forest", temperature: "Hot, Cold, Temparate", traits: "Climber, Camouflage, Hibernating, Antlers, Intelligent")
    Habitat.create(name: "Tundra", temperature: "Cold" , traits: "Fat Reserves, Thick Coat, Hibernating, Burrower, Antlers")
    Habitat.create(name: "Polar", temperature: "Cold", traits: "Fat Reserves, Thick Coat, Swimmer, Hibernating")
    Habitat.create(name: "Desert", temperature: "Hot, Cold", traits: "Broad Feet, Water Reserves, Burrower, Large Ears, Camouflage")
    Habitat.create(name: "Plains", temperature: "Temperate", traits: "Swift Runner, Burrower, Stamina, Camouflage, Migratory, Intelligent")
    Habitat.create(name: "Mountains", temperature: "Cold, Temperate", traits: "Climber, Hibernating, Antlers, Burrower, Thick Coat")
    Habitat.create(name: "Coast", temperature: "Hot, Cold, Temparate", traits: "Aquatic, Swimmer, Camouflage, Webbed Feet")
    Habitat.create(name: "River", temperature: "Cold, Temperate", traits: "Aquatic, Swimmer, Intelligent, Webbed Feet, Migratory")
    Habitat.create(name: "Lake", temperature: "Cold, Temperate", traits: "Aquatic, Swimmer, Webbed Feet")
    Habitat.create(name: "Ocean", temperature: "Cold, Temperate", traits: "Aquatic, Swimmer, Webbed Feet, Bioluminescent, Camouflage, Migratory")

    Size.create(name:"Tiny (Max size < 1 inch Long)", traits:"Eusocial, Parasitic, Mimicry, Symbiotic, Swarming")
    Size.create(name:"Small (Max size < 1 foot Long)", traits:"Fast, Social, Intelligent, Camouflaged, Scavenger, Many Young")
    Size.create(name:"Medium (Max size < 6 foot Long)", traits:"Pack Tactics, Intelligent, Civilised, Pack Territory")
    Size.create(name:"Large (Max size < 15 foot Long)", traits:"Ambusher, Solitary, Slow Digestion, Territory, Migratory, Few Young")
    Size.create(name:"Huge (Max size < 30 ft Long)", traits:"Destructive, Grazer, Solitary, Terrotorial, Lumbering")
    Size.create(name:"Gargantuan (Max Size > 30 ft Long)", traits:"Destructive, Migratory, Implacable, Strips Environment, Provides Ecosystem")