# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


    Animal.create(name: "Aardvark", wings:false, legs:true, tail: true)
    Animal.create(name: "Albatross", wings:true, legs:true, tail: true)
    Animal.create(name: "Alligator", wings:false, legs:true, tail: true)
    Animal.create(name: "Alpaca", wings:false, legs:true, tail: true)
    Animal.create(name: "Ant", wings:true, legs:true, tail: false)
    Animal.create(name: "Anteater", wings:false, legs:true, tail: true)
    Animal.create(name: "Antelope", wings:false, legs:true, tail: false)

    
    Chimera.create(name: "Boris", wings: "Albatross", legs: "Alligator", tail: "Anteater", torso: "Alligator", head: "Alpaca")
    Blender.create(animal_id: 2, chimera_id:1)
    Blender.create(animal_id: 4, chimera_id:1)
    Blender.create(animal_id: 6, chimera_id:1)
    Blender.create(animal_id: 3, chimera_id:1)

    
    
    
    
    
    
    # "Ape",
    #     "Armadillo",
    #     "Donkey",
    #     "Baboon",
    #     "Badger",
    #     "Barracuda",
    #     "Bat",
    #     "Bear",
    #     "Beaver",
    #     "Bee",
    #     "Bison",
    #     "Boar",
    #     "Buffalo",
    #     "Butterfly",
    #     "Camel",
    #     "Capybara",
    #     "Caribou",
    #     "Cassowary",
    #     "Cat",
    #     "Caterpillar",
    #     "Cattle",
    #     "Chamois",
    #     "Cheetah",
    #     "Chicken",
    #     "Chimpanzee",
    #     "Chinchilla",
    #     "Chough",
    #     "Clam",
    #     "Cobra",
    #     "Cockroach",
    #     "Cod",
    #     "Cormorant",
    #     "Coyote",
    #     "Crab",
    #     "Crane",
    #     "Crocodile",
    #     "Crow",
    #     "Curlew",
    #     "Deer",
    #     "Dinosaur",
    #     "Dog",
    #     "Dogfish",
    #     "Dolphin",
    #     "Dotterel",
    #     "Dove",
    #     "Dragonfly",
    #     "Duck",
    #     "Dugong",
    #     "Dunlin",
    #     "Eagle",
    #     "Echidna",
    #     "Eel",
    #     "Eland",
    #     "Elephant",
    #     "Elk",
    #     "Emu",
    #     "Falcon",
    #     "Ferret",
    #     "Finch",
    #     "Fish",
    #     "Flamingo",
    #     "Fly",
    #     "Fox",
    #     "Frog",
    #     "Gaur",
    #     "Gazelle",
    #     "Gerbil",
    #     "Giraffe",
    #     "Gnat",
    #     "Gnu",
    #     "Goat",
    #     "Goldfinch",
    #     "Goldfish",
    #     "Goose",
    #     "Gorilla",
    #     "Goshawk",
    #     "Grasshopper",
    #     "Grouse",
    #     "Guanaco",
    #     "Gull",
    #     "Hamster",
    #     "Hare",
    #     "Hawk",
    #     "Hedgehog",
    #     "Heron",
    #     "Herring",
    #     "Hippopotamus",
    #     "Hornet",
    #     "Horse",
    #     "Human",
    #     "Hummingbird",
    #     "Hyena",
    #     "Ibex",
    #     "Ibis",
    #     "Jackal",
    #     "Jaguar",
    #     "Jay",
    #     "Jellyfish",
    #     "Kangaroo",
    #     "Kingfisher",
    #     "Koala",
    #     "Kookabura",
    #     "Kouprey",
    #     "Kudu",
    #     "Lapwing",
    #     "Lark",
    #     "Lemur",
    #     "Leopard",
    #     "Lion",
    #     "Llama",
    #     "Lobster",
    #     "Locust",
    #     "Loris",
    #     "Louse",
    #     "Lyrebird",
    #     "Magpie",
    #     "Mallard",
    #     "Manatee",
    #     "Mandrill",
    #     "Mantis",
    #     "Marten",
    #     "Meerkat",
    #     "Mink",
    #     "Mole",
    #     "Mongoose",
    #     "Monkey",
    #     "Moose",
    #     "Mosquito",
    #     "Mouse",
    #     "Mule",
    #     "Narwhal",
    #     "Newt",
    #     "Nightingale",
    #     "Octopus",
    #     "Okapi",
    #     "Opossum",
    #     "Oryx",
    #     "Ostrich",
    #     "Otter",
    #     "Owl",
    #     "Oyster",
    #     "Panther",
    #     "Parrot",
    #     "Partridge",
    #     "Peafowl",
    #     "Pelican",
    #     "Penguin",
    #     "Pheasant",
    #     "Pig",
    #     "Pigeon",
    #     "Pony",
    #     "Porcupine",
    #     "Porpoise",
    #     "Quail",
    #     "Quelea",
    #     "Quetzal",
    #     "Rabbit",
    #     "Raccoon",
    #     "Rail",
    #     "Ram",
    #     "Rat",
    #     "Raven",
    #     "Red deer",
    #     "Red panda",
    #     "Reindeer",
    #     "Rhinoceros",
    #     "Rook",
    #     "Salamander",
    #     "Salmon",
    #     "Sand Dollar",
    #     "Sandpiper",
    #     "Sardine",
    #     "Scorpion",
    #     "Seahorse",
    #     "Seal",
    #     "Shark",
    #     "Sheep",
    #     "Shrew",
    #     "Skunk",
    #     "Snail",
    #     "Snake",
    #     "Sparrow",
    #     "Spider",
    #     "Spoonbill",
    #     "Squid",
    #     "Squirrel",
    #     "Starling",
    #     "Stingray",
    #     "Stinkbug",
    #     "Stork",
    #     "Swallow",
    #     "Swan",
    #     "Tapir",
    #     "Tarsier",
    #     "Termite",
    #     "Tiger",
    #     "Toad",
    #     "Trout",
    #     "Turkey",
    #     "Turtle",
    #     "Viper",
    #     "Vulture",
    #     "Wallaby",
    #     "Walrus",
    #     "Wasp",
    #     "Weasel",
    #     "Whale",
    #     "Wildcat",
    #     "Wolf",
    #     "Wolverine",
    #     "Wombat",
    #     "Woodcock",
    #     "Woodpecker",
    #     "Worm",
    #     "Wren",
    #     "Yak",
    #     "Zebra"